public class test01 {
    public static void test01() {
        string dayOfWeek = 'Sat';
        if (dayOfWeek = 'Fri'){
            system.debug('Friday drinks');
        }
        else if (dayOfWeek = 'Sat'){
            system.debug('Sport day');
        }
        else if (dayOfWeek = 'Sun'){
            system.debug('Family day');
        }
        else {
            system.debug('Exciting work');
        }
    }
}